/** Canonical legal document identifiers (versioned registry keys). */
export const LEGAL_DOCUMENT_KEYS = {
  TOS_CUSTOMER: 'TOS-CUSTOMER',
  PRIVACY_POLICY: 'PRIVACY-POLICY',
  AI_CONSENT: 'AI-CONSENT',
  TOS_PROVIDER_DOCTOR: 'TOS-PROVIDER-DOCTOR',
  TOS_PROVIDER_TECHNICIAN: 'TOS-PROVIDER-TECHNICIAN',
  TOS_ADMIN: 'TOS-ADMIN',
  TOS_ENTERPRISE: 'TOS-ENTERPRISE',
} as const;

export type LegalDocumentKey = (typeof LEGAL_DOCUMENT_KEYS)[keyof typeof LEGAL_DOCUMENT_KEYS];

export const LEGAL_CONSENT_TO_DOCUMENT_KEY: Record<string, LegalDocumentKey> = {
  PRIVACY: LEGAL_DOCUMENT_KEYS.PRIVACY_POLICY,
  TERMS: LEGAL_DOCUMENT_KEYS.TOS_CUSTOMER,
  AI_PROCESSING: LEGAL_DOCUMENT_KEYS.AI_CONSENT,
};
