export const FEED_CONSUMPTION_DEFAULT_PAGE = 1;
export const FEED_CONSUMPTION_DEFAULT_LIMIT = 20;
export const FEED_CONSUMPTION_MAX_LIMIT = 100;

export const FEED_CONSUMPTION_ERROR_CODES = {
  NOT_FOUND: 'NOT_FOUND',
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
  DUPLICATE_IDEMPOTENCY: 'DUPLICATE_IDEMPOTENCY',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
} as const;
